#pragma once
#include <SDL.h>
#include <SDL_image.h>
#include <SDL_ttf.h>
#include <SDL_mixer.h>
#include <string>
#include <stdio.h>
#include <ctime>
#include <iostream>
#include <random>
#include <fstream>
#include <cmath>
#include <time.h>
#include <windows.h>
#include <cstdlib>
#include <sstream>
#include <iomanip>
#include <fstream>